fix: ci testing issues

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -84,6 +84,48 @@ jobs:
         env:
           ANSIBLE_FORCE_COLOR: '1'
 
+  test-work-macbook-playbook:
+    runs-on: macos-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v5
+
+      - name: Uninstall GitHub Actions' built-in Homebrew
+        run: sudo /bin/bash tests/uninstall-homebrew.sh
+
+      - name: Uninstall GitHub Actions' built-in browser installs
+        run: |
+          ls -lah /Applications
+          sudo rm -rf /Applications/Firefox.app
+          sudo rm -rf /Applications/Google\ Chrome.app
+          sudo rm -rf /usr/local/bin/firefox
+          sudo rm -rf /usr/local/bin/chromedriver
+
+      - name: Install python and ansible requirements
+        run: |
+          python -m pip install -r requirements.txt
+          ansible-galaxy install -r requirements.yml
+
+      - name: Create .vault_pass.txt
+        run: |
+          echo "${{ secrets.VAULT_PASS }}" > .vault_pass.txt
+
+      - name: Test the work macbook playbook's syntax
+        run: ansible-playbook playbook_work_macbook.yml -i inventory-test.ini --syntax-check
+
+      - name: Test the work macbook playbook
+        run: ansible-playbook playbook_work_macbook.yml -i inventory-test.ini -e "testing=true" -e "admin_password=admin_password user_account_password=" --skip-tags "mas"
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
+
+      - name: Idempotence check for work macbook
+        run: |
+          idempotence=$(mktemp)
+          ansible-playbook playbook_work_macbook.yml -i inventory-test.ini -e "testing=true" -e "admin_password=admin_password user_account_password=" --skip-tags "mas" | tee -a ${idempotence}
+          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+        env:
+          ANSIBLE_FORCE_COLOR: '1'
+
   test-vps-playbook:
     runs-on: ubuntu-latest
     steps:
